local Frame = vgui.Create( "DFrame" )
Frame:SetSize( 500, 400 )
Frame:Center()
Frame:SetTitle( "Admin Menu" )
Frame:SetVisible( true )
Frame:SetDraggable( false )
Frame:ShowCloseButton( true )
Frame:MakePopup()
function Frame:OnClose()
end